local_backend: true

backend:
  name: git-gateway
  branch: editorial_workflow

media_folder: /static/media
public_folder: /media
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    label_singular: post
    folder: content/blog
    create: true
    filter: {field: visibleInCMS, value: true}
    fields: [
      {name: title, widget: string},
      {name: description, widget: text},
      {name: body, widget: markdown},
      {name: visibleInCMS, widget: hidden, default: true}
    ]

  - name: pages
    label: Pages
    files: [
      {name: home, label: Home, file: content/_index.md, fields: [
        {name: title, widget: string},
        {name: welcome, widget: text},
        {name: body, widget: markdown},
      ]},
      {name: about, label: About, file: content/about.md, fields: [
        {name: title, widget: string},
        {name: author, widget: string},
        {name: body, widget: markdown},
      ]},
    ]
